// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.0
// source: oneofs.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//
	//	*Result_Message
	//	*Result_Id
	Result isResult_Result `protobuf_oneof:"result"`
	// Types that are assignable to Test:
	//
	//	*Result_Test1
	//	*Result_Test2
	Test     isResult_Test `protobuf_oneof:"test"`
	Yamamoto int32         `protobuf:"varint,5,opt,name=yamamoto,proto3" json:"yamamoto,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oneofs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_oneofs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_oneofs_proto_rawDescGZIP(), []int{0}
}

func (m *Result) GetResult() isResult_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *Result) GetMessage() string {
	if x, ok := x.GetResult().(*Result_Message); ok {
		return x.Message
	}
	return ""
}

func (x *Result) GetId() uint32 {
	if x, ok := x.GetResult().(*Result_Id); ok {
		return x.Id
	}
	return 0
}

func (m *Result) GetTest() isResult_Test {
	if m != nil {
		return m.Test
	}
	return nil
}

func (x *Result) GetTest1() string {
	if x, ok := x.GetTest().(*Result_Test1); ok {
		return x.Test1
	}
	return ""
}

func (x *Result) GetTest2() string {
	if x, ok := x.GetTest().(*Result_Test2); ok {
		return x.Test2
	}
	return ""
}

func (x *Result) GetYamamoto() int32 {
	if x != nil {
		return x.Yamamoto
	}
	return 0
}

type isResult_Result interface {
	isResult_Result()
}

type Result_Message struct {
	Message string `protobuf:"bytes,1,opt,name=message,proto3,oneof"`
}

type Result_Id struct {
	Id uint32 `protobuf:"varint,2,opt,name=id,proto3,oneof"`
}

func (*Result_Message) isResult_Result() {}

func (*Result_Id) isResult_Result() {}

type isResult_Test interface {
	isResult_Test()
}

type Result_Test1 struct {
	Test1 string `protobuf:"bytes,3,opt,name=test1,proto3,oneof"`
}

type Result_Test2 struct {
	Test2 string `protobuf:"bytes,4,opt,name=test2,proto3,oneof"`
}

func (*Result_Test1) isResult_Test() {}

func (*Result_Test2) isResult_Test() {}

type Result2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//
	//	*Result2_Message
	//	*Result2_Id
	Result isResult2_Result `protobuf_oneof:"result"`
	// Types that are assignable to Test:
	//
	//	*Result2_Test1
	//	*Result2_Test2
	Test     isResult2_Test `protobuf_oneof:"test"`
	Yamamoto int32          `protobuf:"varint,5,opt,name=yamamoto,proto3" json:"yamamoto,omitempty"`
	Ascii    string         `protobuf:"bytes,6,opt,name=Ascii,proto3" json:"Ascii,omitempty"`
}

func (x *Result2) Reset() {
	*x = Result2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oneofs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result2) ProtoMessage() {}

func (x *Result2) ProtoReflect() protoreflect.Message {
	mi := &file_oneofs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result2.ProtoReflect.Descriptor instead.
func (*Result2) Descriptor() ([]byte, []int) {
	return file_oneofs_proto_rawDescGZIP(), []int{1}
}

func (m *Result2) GetResult() isResult2_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *Result2) GetMessage() string {
	if x, ok := x.GetResult().(*Result2_Message); ok {
		return x.Message
	}
	return ""
}

func (x *Result2) GetId() uint32 {
	if x, ok := x.GetResult().(*Result2_Id); ok {
		return x.Id
	}
	return 0
}

func (m *Result2) GetTest() isResult2_Test {
	if m != nil {
		return m.Test
	}
	return nil
}

func (x *Result2) GetTest1() string {
	if x, ok := x.GetTest().(*Result2_Test1); ok {
		return x.Test1
	}
	return ""
}

func (x *Result2) GetTest2() string {
	if x, ok := x.GetTest().(*Result2_Test2); ok {
		return x.Test2
	}
	return ""
}

func (x *Result2) GetYamamoto() int32 {
	if x != nil {
		return x.Yamamoto
	}
	return 0
}

func (x *Result2) GetAscii() string {
	if x != nil {
		return x.Ascii
	}
	return ""
}

type isResult2_Result interface {
	isResult2_Result()
}

type Result2_Message struct {
	Message string `protobuf:"bytes,1,opt,name=message,proto3,oneof"`
}

type Result2_Id struct {
	Id uint32 `protobuf:"varint,2,opt,name=id,proto3,oneof"`
}

func (*Result2_Message) isResult2_Result() {}

func (*Result2_Id) isResult2_Result() {}

type isResult2_Test interface {
	isResult2_Test()
}

type Result2_Test1 struct {
	Test1 string `protobuf:"bytes,3,opt,name=test1,proto3,oneof"`
}

type Result2_Test2 struct {
	Test2 string `protobuf:"bytes,4,opt,name=test2,proto3,oneof"`
}

func (*Result2_Test1) isResult2_Test() {}

func (*Result2_Test2) isResult2_Test() {}

var File_oneofs_proto protoreflect.FileDescriptor

var file_oneofs_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e,
	0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x73, 0x22, 0x94,
	0x01, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1a, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x05, 0x74, 0x65, 0x73, 0x74, 0x31,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x05, 0x74, 0x65, 0x73, 0x74, 0x31, 0x12,
	0x16, 0x0a, 0x05, 0x74, 0x65, 0x73, 0x74, 0x32, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01,
	0x52, 0x05, 0x74, 0x65, 0x73, 0x74, 0x32, 0x12, 0x1a, 0x0a, 0x08, 0x79, 0x61, 0x6d, 0x61, 0x6d,
	0x6f, 0x74, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x79, 0x61, 0x6d, 0x61, 0x6d,
	0x6f, 0x74, 0x6f, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x06, 0x0a,
	0x04, 0x74, 0x65, 0x73, 0x74, 0x22, 0xab, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x32, 0x12, 0x1a, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x05, 0x74, 0x65, 0x73, 0x74, 0x31, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01,
	0x52, 0x05, 0x74, 0x65, 0x73, 0x74, 0x31, 0x12, 0x16, 0x0a, 0x05, 0x74, 0x65, 0x73, 0x74, 0x32,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x05, 0x74, 0x65, 0x73, 0x74, 0x32, 0x12,
	0x1a, 0x0a, 0x08, 0x79, 0x61, 0x6d, 0x61, 0x6d, 0x6f, 0x74, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x79, 0x61, 0x6d, 0x61, 0x6d, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x41,
	0x73, 0x63, 0x69, 0x69, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x41, 0x73, 0x63, 0x69,
	0x69, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x06, 0x0a, 0x04, 0x74,
	0x65, 0x73, 0x74, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x43, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2d, 0x4a, 0x65, 0x61, 0x6e, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x5f, 0x67, 0x6f, 0x5f, 0x74, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61,
	0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_oneofs_proto_rawDescOnce sync.Once
	file_oneofs_proto_rawDescData = file_oneofs_proto_rawDesc
)

func file_oneofs_proto_rawDescGZIP() []byte {
	file_oneofs_proto_rawDescOnce.Do(func() {
		file_oneofs_proto_rawDescData = protoimpl.X.CompressGZIP(file_oneofs_proto_rawDescData)
	})
	return file_oneofs_proto_rawDescData
}

var file_oneofs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_oneofs_proto_goTypes = []interface{}{
	(*Result)(nil),  // 0: example.oneofs.Result
	(*Result2)(nil), // 1: example.oneofs.Result2
}
var file_oneofs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_oneofs_proto_init() }
func file_oneofs_proto_init() {
	if File_oneofs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_oneofs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oneofs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_oneofs_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Result_Message)(nil),
		(*Result_Id)(nil),
		(*Result_Test1)(nil),
		(*Result_Test2)(nil),
	}
	file_oneofs_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Result2_Message)(nil),
		(*Result2_Id)(nil),
		(*Result2_Test1)(nil),
		(*Result2_Test2)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_oneofs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_oneofs_proto_goTypes,
		DependencyIndexes: file_oneofs_proto_depIdxs,
		MessageInfos:      file_oneofs_proto_msgTypes,
	}.Build()
	File_oneofs_proto = out.File
	file_oneofs_proto_rawDesc = nil
	file_oneofs_proto_goTypes = nil
	file_oneofs_proto_depIdxs = nil
}
